package com.epam.lab.service.serviceimpl;

import com.epam.lab.service.model.WalletService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "SoapServiceImplService", targetNamespace = "http://serviceimpl.service.lab.epam.com/", wsdlLocation = "http://localhost:8080/OlehSikorskyiService/wallet?wsdl")
public class SoapServiceImplService
        extends Service {

    private final static URL SOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SOAPSERVICEIMPLSERVICE_QNAME = new QName("http://serviceimpl.service.lab.epam.com/", "SoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/OlehSikorskyiService/wallet?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SoapServiceImplService() {
        super(__getWsdlLocation(), SOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPSERVICEIMPLSERVICE_QNAME);
    }

    public SoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public SoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns WalletService
     */
    @WebEndpoint(name = "SoapServiceImplPort")
    public WalletService getSoapServiceImplPort() {
        return super.getPort(new QName("http://serviceimpl.service.lab.epam.com/", "SoapServiceImplPort"), WalletService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns WalletService
     */
    @WebEndpoint(name = "SoapServiceImplPort")
    public WalletService getSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.service.lab.epam.com/", "SoapServiceImplPort"), WalletService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw SOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
