
package com.epam.lab.service.serviceimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.epam.lab.service.ObjectFactory;
import com.epam.lab.service.SummaryWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WalletService", targetNamespace = "http://service.lab.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WalletService {


    /**
     * 
     * @return
     *     returns com.epam.lab.service.SummaryWrapper
     */
    @WebMethod(action = "checkBalance")
    @WebResult(partName = "return")
    public SummaryWrapper checkBalance();

    /**
     * 
     * @param money
     * @return
     *     returns com.epam.lab.service.SummaryWrapper
     */
    @WebMethod(action = "withdrawMoney")
    @WebResult(partName = "return")
    public SummaryWrapper withdrawMoney(
        @WebParam(name = "money", partName = "money")
        double money);

    /**
     * 
     * @param money
     * @return
     *     returns com.epam.lab.service.SummaryWrapper
     */
    @WebMethod(action = "refillAccount")
    @WebResult(partName = "return")
    public SummaryWrapper refillAccount(
        @WebParam(name = "money", partName = "money")
        double money);

}
